mongodb:
  connection_string: 'mongodb://localhost:27017/'
  database: 'bidding_engine'
  tables: ['auction', 'bidding']
bidding_service:
  interval: 5
ecommerce: 
  url: 'http://192.168.29.215:5000/'


