mysql_host: 'grocart.ch3oiigz5sxw.ap-south-1.rds.amazonaws.com'
mysql_user: 'admin'
# Enter your password in field below
mysql_password: 'adminadmin'
mysql_db: 'grocart'
#recommendationServiceUrl : 'http://localhost:8000/predict'
recommendationServiceUrl : 'http://ec2-3-108-60-208.ap-south-1.compute.amazonaws.com:8000/predict'
#userProductRecommendationServiceUrl : 'http://localhost:8000/predictuser'
userProductRecommendationServiceUrl : 'http://ec2-3-108-60-208.ap-south-1.compute.amazonaws.com:8000/predictuser'
